name: Conditional Test Runner

on:
  pull_request:
    paths:
      - 'src/**'

jobs:
  run-conditional-tests:
    runs-on: ubuntu-latest

    outputs:
      problem-path: ${{ steps.find-problem.outputs.problem-path }}
      language: ${{ steps.find-language.outputs.language }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Find Problem
        id: find-problem
        run: |
          PROBLEM_PATH=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '^src/' | awk -F/ '/' '{print $2}' | uniq)
          echo "::set-output name=problem-path::src/$PROBLEM_PATH"

      - name: Find Language
        id: find-language
        run: |
          LANGUAGE=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '^src/' | awk -F/ '/' '{print $3}' | uniq)
          echo "::set-output name=language::$LANGUAGE"

  setup-and-test:
    needs: run-conditional-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [csharp, golang, java, node, python]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        if: needs.run-conditional-tests.outputs.language == 'csharp'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' # specify your dotnet version

      - name: Set up Go
        if: needs.run-conditional-tests.outputs.language == 'golang'
        uses: actions/setup-go@v2
        with:
          go-version: '1.16' # specify your Go version

      - name: Set up Java
        if: needs.run-conditional-tests.outputs.language == 'java'
        uses: actions/setup-java@v1
        with:
          java-version: '11' # specify your Java version

      - name: Set up Node.js
        if: needs.run-conditional-tests.outputs.language == 'node'
        uses: actions/setup-node@v2
        with:
          node-version: '14' # specify your Node.js version

      - name: Set up Python
        if: needs.run-conditional-tests.outputs.language == 'python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # specify your Python version

      - name: Install dependencies and run .NET tests
        if: needs.run-conditional-tests.outputs.language == 'csharp'
        run: dotnet test ${{ needs.run-conditional-tests.outputs.problem-path }}/csharp/

      - name: Install dependencies and run Go tests
        if: needs.run-conditional-tests.outputs.language == 'golang'
        run: go test ${{ needs.run-conditional-tests.outputs.problem-path }}/golang/...

      - name: Install dependencies and run Java tests
        if: needs.run-conditional-tests.outputs.language == 'java'
        run: mvn -f ${{ needs.run-conditional-tests.outputs.problem-path }}/java/pom.xml test

      - name: Install dependencies and run Node.js tests
        if: needs.run-conditional-tests.outputs.language == 'node'
        run: npm install && npm test --prefix ${{ needs.run-conditional-tests.outputs.problem-path }}/node/

      - name: Install dependencies and run Python tests
        if: needs.run-conditional-tests.outputs.language == 'python'
        run: pip install -r ${{ needs.run-conditional-tests.outputs.problem-path }}/python/requirements.txt && pytest ${{ needs.run-conditional-tests.outputs.problem-path }}/python/
